run_name: ???
hydra:
  mode: ${hydra.mode}
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}___${run_name}
  sweep:
    dir: ./hydra_multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}___${run_name}
    subdir: ${hydra.job.num}

device: cuda:1
defaults:
  - guidance_cfg: exp17_adain_colorisation
  - samples: empty_prompt

scheduler_name: ddim_50_eps
model_name: stable-diffusion-v1-4

exp_configs:
  qkv_guider_start: 25
  qkv_guider_end: 50
  qkv_guider_scale: 75.0
