run_name: ???
hydra:
  mode: ${hydra.mode}
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}=${run_name}
  sweep:
    dir: ./hydra_multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

device: cuda:0

defaults:
  - guidance_cfg: exp3_ctrl_style
  - samples: 

scheduler_name: ddim_50_eps
model_name: stable-diffusion-v1-4